name: AppImage

on:
  push:
    branches: [ master, appimage ]
  pull_request:
    branches: [ master ]

jobs:
  build-appimage:

    runs-on: ubuntu-latest
    container:
      image: appimagecrafters/appimage-builder

    steps:
      - name: install dependencies
        run: |
          apt update
          apt install -y software-properties-common
          add-apt-repository ppa:ubuntu-toolchain-r/test
          apt install -y build-essential python3-pip libxml2-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libglu1-mesa-dev freeglut3-dev mesa-common-dev gcc-10 g++-10
          pip3 install --upgrade pip cmake
          update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 10
          update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 10
      - uses: actions/checkout@v1
        with:
          submodules: "recursive"
      - name: Configure
        run: cmake -S . -DCMAKE_CXX_COMPILER=g++-10 -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr
      - name: build
        run: make -j4  install DESTDIR=AppDir
      - name: pack
        run: |
          export export UPDATE_INFO="gh-releases-zsync|brenthuisman|arbor-gui|latest|*.AppImage.zsync"
          appimage-builder --skip-test
      - uses: actions/upload-artifact@v2
        with:
          name: AppImage
          path: './*.AppImage*'

